// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: OilChangerDisplayUI

#ifndef _OILCHANGERDISPLAYUI_UI_H
#define _OILCHANGERDISPLAYUI_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"
void Particle1_Animation(lv_obj_t * TargetObject, int delay);
void Particle2_Animation(lv_obj_t * TargetObject, int delay);
void Particle3_Animation(lv_obj_t * TargetObject, int delay);
void ButtonFlash_Animation(lv_obj_t * TargetObject, int delay);
void Wave1_Animation(lv_obj_t * TargetObject, int delay);
void Wave2_Animation(lv_obj_t * TargetObject, int delay);
void Off_Animation(lv_obj_t * TargetObject, int delay);
void On_Animation(lv_obj_t * TargetObject, int delay);
// SCREEN: ui_Main
void ui_Main_screen_init(void);
void ui_event_Main(lv_event_t * e);
extern lv_obj_t * ui_Main;
extern lv_obj_t * ui_BG1;
extern lv_obj_t * ui_Fill_Capacity_Number_2;
extern lv_obj_t * ui_Fill_Capacity_Number_1;
extern lv_obj_t * ui_Label_Fill_Capacity;
extern lv_obj_t * ui_Label_Fill_Capacity_Unit;
extern lv_obj_t * ui_Slider_Extract;
extern lv_obj_t * ui_Slider_Fill;
extern lv_obj_t * ui_Group_Extract_Percent;
extern lv_obj_t * ui_Label_Extract_Percent_1;
extern lv_obj_t * ui_Label_Extract_Percent_2;
extern lv_obj_t * ui_Label_Extract_Percent_3;
extern lv_obj_t * ui_Label_Extract_Percent_4;
extern lv_obj_t * ui_Label_Extract_Percent_5;
extern lv_obj_t * ui_Group_Header;
extern lv_obj_t * ui_Label_Time;
extern lv_obj_t * ui_LabeL_PM;
extern lv_obj_t * ui_Label_Temp;
extern lv_obj_t * ui_Label_Celsius;
extern lv_obj_t * ui_Label_Top_Left_Title;
extern lv_obj_t * ui_Group_Footer;
extern lv_obj_t * ui_Image_Battery_icon;
extern lv_obj_t * ui_Battery_Voltage_Number;
extern lv_obj_t * ui_Unit_Label_Battery_Voltage;
extern lv_obj_t * ui_Nav_Button_Group;
extern lv_obj_t * ui_BTN_Driving;
void ui_event_BTN_BG1(lv_event_t * e);
extern lv_obj_t * ui_BTN_BG1;
extern lv_obj_t * ui_ICN_Driving;
extern lv_obj_t * ui_BTN_Diagnostics;
void ui_event_BTN_BG2(lv_event_t * e);
extern lv_obj_t * ui_BTN_BG2;
extern lv_obj_t * ui_Icon_Diagnostics;
extern lv_obj_t * ui_BTN_Lock;
void ui_event_BTN_BG3(lv_event_t * e);
extern lv_obj_t * ui_BTN_BG3;
extern lv_obj_t * ui_ICN_Lock;
extern lv_obj_t * ui_Group_Oil_Change_Data_Panel;
extern lv_obj_t * ui_Group_Info_Panel_Title;
extern lv_obj_t * ui_Underline_Title_Oil_Change;
extern lv_obj_t * ui_Label_Oil_Change_Information;
extern lv_obj_t * ui_Group_Oil_Change_Info_Content;
extern lv_obj_t * ui_Group_Battery_Voltage;
extern lv_obj_t * ui_Label_Flow_Rate;
extern lv_obj_t * ui_Flow_Rate_Number;
extern lv_obj_t * ui_Unit_Label_Flow_Rate;
extern lv_obj_t * ui_Group_Oil_Temp;
extern lv_obj_t * ui_Label_Oil_Temp;
extern lv_obj_t * ui_Oil_Temp_Number;
extern lv_obj_t * ui_Label_Unit_Celcius;
extern lv_obj_t * ui_Group_Amount_Filled;
extern lv_obj_t * ui_Label_Filled;
extern lv_obj_t * ui_Amount_Filled_Number;
extern lv_obj_t * ui_Unit_Label_Litres;
extern lv_obj_t * ui_Group_Amount_Extracted;
extern lv_obj_t * ui_Label_Extracted;
extern lv_obj_t * ui_Amount_Extracted_Number;
extern lv_obj_t * ui_Unit_Label_Extracted_Litres;
extern lv_obj_t * ui_Group_ETA;
extern lv_obj_t * ui_Label_ETA;
extern lv_obj_t * ui_ETA_Time;
extern lv_obj_t * ui_Group_Run_Time;
extern lv_obj_t * ui_Label_Run_Time;
extern lv_obj_t * ui_Run_Time;
extern lv_obj_t * ui_Group_Diagnostics;
extern lv_obj_t * ui_Group_Diagnostics_Information;
extern lv_obj_t * ui_Title_BG1;
extern lv_obj_t * ui_Label_Diagnostics_Title;
extern lv_obj_t * ui_Group_Content1;
extern lv_obj_t * ui_Group_Charging;
extern lv_obj_t * ui_LabeL_Charging;
extern lv_obj_t * ui_Label_Charging_Number;
extern lv_obj_t * ui_Label_Percent1;
extern lv_obj_t * ui_Group_Distance;
extern lv_obj_t * ui_Label_Distance;
extern lv_obj_t * ui_Label_Distance_Number;
extern lv_obj_t * ui_Label_km4;
extern lv_obj_t * ui_Group_Complete;
extern lv_obj_t * ui_Label_Complete;
extern lv_obj_t * ui_Label_Complete_Number;
extern lv_obj_t * ui_Label_Mins;
extern lv_obj_t * ui_Group_Battery_Indicator;
extern lv_obj_t * ui_Particle_Group;
extern lv_obj_t * ui_Image_Particle1;
extern lv_obj_t * ui_Wave_Group;
extern lv_obj_t * ui_Wave1;
extern lv_obj_t * ui_Image_Particle2;
extern lv_obj_t * ui_Wave2;
extern lv_obj_t * ui_Image_Particle3;
extern lv_obj_t * ui_Image_Battery_BG;
extern lv_obj_t * ui_Image_Flash;
extern lv_obj_t * ui_Group_Pin_Code;
extern lv_obj_t * ui_Group_Admin_Title;
extern lv_obj_t * ui_Title_BG2;
extern lv_obj_t * ui_Label_Unlock;
extern lv_obj_t * ui_Group_Pin_Numbers;
void ui_event_Button_Pin_Code_1(lv_event_t * e);
extern lv_obj_t * ui_Button_Pin_Code_1;
extern lv_obj_t * ui_Label_1;
extern lv_obj_t * ui_Pin_Add1;
void ui_event_Button_Pin_Code_2(lv_event_t * e);
extern lv_obj_t * ui_Button_Pin_Code_2;
extern lv_obj_t * ui_Label_2;
extern lv_obj_t * ui_Pin_Add2;
void ui_event_Button_Pin_Code_3(lv_event_t * e);
extern lv_obj_t * ui_Button_Pin_Code_3;
extern lv_obj_t * ui_Label_3;
extern lv_obj_t * ui_Pin_Add3;
void ui_event_Button_Pin_Code_4(lv_event_t * e);
extern lv_obj_t * ui_Button_Pin_Code_4;
extern lv_obj_t * ui_Label_4;
extern lv_obj_t * ui_Pin_Add4;
void ui_event_Button_Pin_Code_5(lv_event_t * e);
extern lv_obj_t * ui_Button_Pin_Code_5;
extern lv_obj_t * ui_Label_5;
extern lv_obj_t * ui_Pin_Add5;
void ui_event_Button_Pin_Code_6(lv_event_t * e);
extern lv_obj_t * ui_Button_Pin_Code_6;
extern lv_obj_t * ui_Label_6;
extern lv_obj_t * ui_Pin_Add6;
void ui_event_Button_Pin_Code_7(lv_event_t * e);
extern lv_obj_t * ui_Button_Pin_Code_7;
extern lv_obj_t * ui_Label_7;
extern lv_obj_t * ui_Pin_Add7;
void ui_event_Button_Pin_Code_8(lv_event_t * e);
extern lv_obj_t * ui_Button_Pin_Code_8;
extern lv_obj_t * ui_Label_8;
extern lv_obj_t * ui_Pin_Add8;
void ui_event_Button_Pin_Code_9(lv_event_t * e);
extern lv_obj_t * ui_Button_Pin_Code_9;
extern lv_obj_t * ui_Label_9;
extern lv_obj_t * ui_Pin_Add9;
void ui_event_Button_Pin_Code_X(lv_event_t * e);
extern lv_obj_t * ui_Button_Pin_Code_X;
extern lv_obj_t * ui_Pin_Add10;
extern lv_obj_t * ui_Image_X;
void ui_event_Button_Pin_Code_0(lv_event_t * e);
extern lv_obj_t * ui_Button_Pin_Code_0;
extern lv_obj_t * ui_Label_0;
extern lv_obj_t * ui_Pin_Add11;
void ui_event_Button_Pin_Code_Confirm(lv_event_t * e);
extern lv_obj_t * ui_Button_Pin_Code_Confirm;
extern lv_obj_t * ui_Pin_Add12;
extern lv_obj_t * ui_Image_Ok;
void ui_event____initial_actions0(lv_event_t * e);
extern lv_obj_t * ui____initial_actions0;

LV_IMG_DECLARE(ui_img_ebike_bg_png);    // assets\ebike_bg.png
LV_IMG_DECLARE(ui_img_speed_slider_png);    // assets\speed_slider.png
LV_IMG_DECLARE(ui_img_slider_battery_png);    // assets\slider_battery.png
LV_IMG_DECLARE(ui_img_icn_flash_png);    // assets\icn_flash.png
LV_IMG_DECLARE(ui_img_menu_on_png);    // assets\menu_on.png
LV_IMG_DECLARE(ui_img_icon_oilchange_png);    // assets\icon_oilchange.png
LV_IMG_DECLARE(ui_img_190876488);    // assets\icon-diagnostics.png
LV_IMG_DECLARE(ui_img_icn_lock_png);    // assets\icn_lock.png
LV_IMG_DECLARE(ui_img_menu_line_png);    // assets\menu_line.png
LV_IMG_DECLARE(ui_img_particle_1_png);    // assets\particle_1.png
LV_IMG_DECLARE(ui_img_water_2_png);    // assets\water_2.png
LV_IMG_DECLARE(ui_img_particle_3_png);    // assets\particle_3.png
LV_IMG_DECLARE(ui_img_water_1_png);    // assets\water_1.png
LV_IMG_DECLARE(ui_img_particle_2_png);    // assets\particle_2.png
LV_IMG_DECLARE(ui_img_battery_bg_png);    // assets\battery_bg.png
LV_IMG_DECLARE(ui_img_icn_charge_png);    // assets\icn_charge.png
LV_IMG_DECLARE(ui_img_pin_line_png);    // assets\pin_line.png
LV_IMG_DECLARE(ui_img_pin_on_png);    // assets\pin_on.png
LV_IMG_DECLARE(ui_img_icn_x_png);    // assets\icn_x.png
LV_IMG_DECLARE(ui_img_icn_ok_png);    // assets\icn_ok.png

LV_FONT_DECLARE(ui_font_Big);
LV_FONT_DECLARE(ui_font_Medium);
LV_FONT_DECLARE(ui_font_Number);
LV_FONT_DECLARE(ui_font_Small);

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
