// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: OilChangerDisplayUI

#include "../ui.h"

void ui_Main_screen_init(void)
{
    ui_Main = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Main, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BG1 = lv_img_create(ui_Main);
    lv_img_set_src(ui_BG1, &ui_img_ebike_bg_png);
    lv_obj_set_width(ui_BG1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BG1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_BG1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BG1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_BG1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Fill_Capacity_Number_2 = lv_label_create(ui_Main);
    lv_obj_set_width(ui_Fill_Capacity_Number_2, 100);
    lv_obj_set_height(ui_Fill_Capacity_Number_2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Fill_Capacity_Number_2, -32);
    lv_obj_set_y(ui_Fill_Capacity_Number_2, 8);
    lv_obj_set_align(ui_Fill_Capacity_Number_2, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_Fill_Capacity_Number_2, LV_LABEL_LONG_CLIP);
    lv_label_set_text(ui_Fill_Capacity_Number_2, "4.0");
    lv_obj_set_style_text_color(ui_Fill_Capacity_Number_2, lv_color_hex(0xD56920), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Fill_Capacity_Number_2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Fill_Capacity_Number_2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Fill_Capacity_Number_2, &ui_font_Number, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Fill_Capacity_Number_1 = lv_label_create(ui_Main);
    lv_obj_set_width(ui_Fill_Capacity_Number_1, 100);
    lv_obj_set_height(ui_Fill_Capacity_Number_1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Fill_Capacity_Number_1, -38);
    lv_obj_set_y(ui_Fill_Capacity_Number_1, 8);
    lv_obj_set_align(ui_Fill_Capacity_Number_1, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_Fill_Capacity_Number_1, LV_LABEL_LONG_CLIP);
    lv_label_set_text(ui_Fill_Capacity_Number_1, "4.0");
    lv_obj_set_style_text_color(ui_Fill_Capacity_Number_1, lv_color_hex(0xFFE69C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Fill_Capacity_Number_1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Fill_Capacity_Number_1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Fill_Capacity_Number_1, &ui_font_Number, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_Fill_Capacity = lv_label_create(ui_Main);
    lv_obj_set_width(ui_Label_Fill_Capacity, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Fill_Capacity, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_Fill_Capacity, -30);
    lv_obj_set_y(ui_Label_Fill_Capacity, -60);
    lv_obj_set_align(ui_Label_Fill_Capacity, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_Fill_Capacity, "Fill Capacity");
    lv_obj_set_style_text_color(ui_Label_Fill_Capacity, lv_color_hex(0x94AEB4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_Fill_Capacity, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Fill_Capacity, &ui_font_Medium, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_Fill_Capacity_Unit = lv_label_create(ui_Main);
    lv_obj_set_width(ui_Label_Fill_Capacity_Unit, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Fill_Capacity_Unit, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_Fill_Capacity_Unit, -13);
    lv_obj_set_y(ui_Label_Fill_Capacity_Unit, 58);
    lv_obj_set_align(ui_Label_Fill_Capacity_Unit, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_Fill_Capacity_Unit, "Litres");
    lv_obj_set_style_text_color(ui_Label_Fill_Capacity_Unit, lv_color_hex(0x94AEB4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_Fill_Capacity_Unit, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Fill_Capacity_Unit, &ui_font_Medium, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Slider_Extract = lv_slider_create(ui_Main);
    lv_slider_set_range(ui_Slider_Extract, 0, 1000);
    lv_slider_set_value(ui_Slider_Extract, 1000, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Slider_Extract) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Slider_Extract, 0,
                                                                                                   LV_ANIM_OFF);
    lv_obj_set_width(ui_Slider_Extract, 123);
    lv_obj_set_height(ui_Slider_Extract, 244);
    lv_obj_set_x(ui_Slider_Extract, -100);
    lv_obj_set_y(ui_Slider_Extract, -1);
    lv_obj_set_align(ui_Slider_Extract, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Slider_Extract, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider_Extract, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Slider_Extract, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider_Extract, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Slider_Extract, &ui_img_speed_slider_png, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Slider_Extract, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider_Extract, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Slider_Fill = lv_slider_create(ui_Main);
    lv_slider_set_range(ui_Slider_Fill, 0, 1000);
    lv_obj_set_width(ui_Slider_Fill, 106);
    lv_obj_set_height(ui_Slider_Fill, 235);
    lv_obj_set_x(ui_Slider_Fill, -147);
    lv_obj_set_y(ui_Slider_Fill, 1);
    lv_obj_set_align(ui_Slider_Fill, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Slider_Fill, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider_Fill, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Slider_Fill, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider_Fill, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Slider_Fill, &ui_img_slider_battery_png, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Slider_Fill, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider_Fill, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Group_Extract_Percent = lv_obj_create(ui_Main);
    lv_obj_set_width(ui_Group_Extract_Percent, 107);
    lv_obj_set_height(ui_Group_Extract_Percent, 200);
    lv_obj_set_align(ui_Group_Extract_Percent, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_Group_Extract_Percent, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Group_Extract_Percent, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Group_Extract_Percent, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_Extract_Percent_1 = lv_label_create(ui_Group_Extract_Percent);
    lv_obj_set_width(ui_Label_Extract_Percent_1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Extract_Percent_1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_Extract_Percent_1, 21);
    lv_obj_set_y(ui_Label_Extract_Percent_1, 0);
    lv_obj_set_align(ui_Label_Extract_Percent_1, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Label_Extract_Percent_1, "100#94aeb4 %");
    lv_label_set_recolor(ui_Label_Extract_Percent_1, "true");
    lv_obj_set_style_text_color(ui_Label_Extract_Percent_1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_Extract_Percent_1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Extract_Percent_1, &ui_font_Small, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_Extract_Percent_2 = lv_label_create(ui_Group_Extract_Percent);
    lv_obj_set_width(ui_Label_Extract_Percent_2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Extract_Percent_2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_Extract_Percent_2, -5);
    lv_obj_set_y(ui_Label_Extract_Percent_2, lv_pct(22));
    lv_obj_set_align(ui_Label_Extract_Percent_2, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Label_Extract_Percent_2, "75#94aeb4 %");
    lv_label_set_recolor(ui_Label_Extract_Percent_2, "true");
    lv_obj_set_style_text_color(ui_Label_Extract_Percent_2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_Extract_Percent_2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Extract_Percent_2, &ui_font_Small, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_Extract_Percent_3 = lv_label_create(ui_Group_Extract_Percent);
    lv_obj_set_width(ui_Label_Extract_Percent_3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Extract_Percent_3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_Extract_Percent_3, -29);
    lv_obj_set_y(ui_Label_Extract_Percent_3, lv_pct(50));
    lv_obj_set_align(ui_Label_Extract_Percent_3, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Label_Extract_Percent_3, "50#94aeb4 %");
    lv_label_set_recolor(ui_Label_Extract_Percent_3, "true");
    lv_obj_set_style_text_color(ui_Label_Extract_Percent_3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_Extract_Percent_3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Extract_Percent_3, &ui_font_Small, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_Extract_Percent_4 = lv_label_create(ui_Group_Extract_Percent);
    lv_obj_set_width(ui_Label_Extract_Percent_4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Extract_Percent_4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_Extract_Percent_4, -8);
    lv_obj_set_y(ui_Label_Extract_Percent_4, lv_pct(74));
    lv_obj_set_align(ui_Label_Extract_Percent_4, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Label_Extract_Percent_4, "25#94aeb4 %");
    lv_label_set_recolor(ui_Label_Extract_Percent_4, "true");
    lv_obj_set_style_text_color(ui_Label_Extract_Percent_4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_Extract_Percent_4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Extract_Percent_4, &ui_font_Small, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_Extract_Percent_5 = lv_label_create(ui_Group_Extract_Percent);
    lv_obj_set_width(ui_Label_Extract_Percent_5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Extract_Percent_5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_Extract_Percent_5, 27);
    lv_obj_set_y(ui_Label_Extract_Percent_5, lv_pct(94));
    lv_obj_set_align(ui_Label_Extract_Percent_5, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Label_Extract_Percent_5, "0#94aeb4 %");
    lv_label_set_recolor(ui_Label_Extract_Percent_5, "true");
    lv_obj_set_style_text_color(ui_Label_Extract_Percent_5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_Extract_Percent_5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Extract_Percent_5, &ui_font_Small, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Group_Header = lv_obj_create(ui_Main);
    lv_obj_set_height(ui_Group_Header, 24);
    lv_obj_set_width(ui_Group_Header, lv_pct(100));
    lv_obj_set_align(ui_Group_Header, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_Group_Header, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Group_Header, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Group_Header, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Group_Header, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Group_Header, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Group_Header, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Group_Header, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_Time = lv_label_create(ui_Group_Header);
    lv_obj_set_width(ui_Label_Time, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Time, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_Time, -28);
    lv_obj_set_y(ui_Label_Time, 0);
    lv_obj_set_align(ui_Label_Time, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_Label_Time, "11:45");
    lv_obj_set_style_text_color(ui_Label_Time, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_Time, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Time, &ui_font_Medium, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabeL_PM = lv_label_create(ui_Group_Header);
    lv_obj_set_width(ui_LabeL_PM, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabeL_PM, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabeL_PM, -7);
    lv_obj_set_y(ui_LabeL_PM, 0);
    lv_obj_set_align(ui_LabeL_PM, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_LabeL_PM, "AM");
    lv_obj_set_style_text_color(ui_LabeL_PM, lv_color_hex(0x94AEB4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabeL_PM, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabeL_PM, &ui_font_Small, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_Temp = lv_label_create(ui_Group_Header);
    lv_obj_set_width(ui_Label_Temp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Temp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_Temp, -100);
    lv_obj_set_y(ui_Label_Temp, 0);
    lv_obj_set_align(ui_Label_Temp, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_Label_Temp, "+32.7");
    lv_obj_set_style_text_color(ui_Label_Temp, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_Temp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Temp, &ui_font_Medium, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_Celsius = lv_label_create(ui_Group_Header);
    lv_obj_set_width(ui_Label_Celsius, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Celsius, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_Celsius, -84);
    lv_obj_set_y(ui_Label_Celsius, 0);
    lv_obj_set_align(ui_Label_Celsius, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_Label_Celsius, "°C");
    lv_obj_set_style_text_color(ui_Label_Celsius, lv_color_hex(0x94AEB4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_Celsius, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Celsius, &ui_font_Small, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_Top_Left_Title = lv_label_create(ui_Group_Header);
    lv_obj_set_width(ui_Label_Top_Left_Title, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Top_Left_Title, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_Top_Left_Title, -5);
    lv_obj_set_y(ui_Label_Top_Left_Title, 0);
    lv_obj_set_align(ui_Label_Top_Left_Title, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label_Top_Left_Title, "Oil Changer");
    lv_obj_set_style_text_color(ui_Label_Top_Left_Title, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_Top_Left_Title, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Top_Left_Title, &ui_font_Small, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Group_Footer = lv_obj_create(ui_Main);
    lv_obj_set_height(ui_Group_Footer, 40);
    lv_obj_set_width(ui_Group_Footer, lv_pct(100));
    lv_obj_set_align(ui_Group_Footer, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_Group_Footer, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Group_Footer, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Group_Footer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image_Battery_icon = lv_img_create(ui_Group_Footer);
    lv_img_set_src(ui_Image_Battery_icon, &ui_img_icn_flash_png);
    lv_obj_set_width(ui_Image_Battery_icon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image_Battery_icon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image_Battery_icon, 7);
    lv_obj_set_y(ui_Image_Battery_icon, 7);
    lv_obj_set_align(ui_Image_Battery_icon, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_Image_Battery_icon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image_Battery_icon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Battery_Voltage_Number = lv_label_create(ui_Group_Footer);
    lv_obj_set_width(ui_Battery_Voltage_Number, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Battery_Voltage_Number, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Battery_Voltage_Number, -418);
    lv_obj_set_y(ui_Battery_Voltage_Number, 7);
    lv_obj_set_align(ui_Battery_Voltage_Number, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_Battery_Voltage_Number, "28.6");
    lv_obj_set_style_text_color(ui_Battery_Voltage_Number, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Battery_Voltage_Number, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Battery_Voltage_Number, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Battery_Voltage_Number, &ui_font_Big, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Unit_Label_Battery_Voltage = lv_label_create(ui_Group_Footer);
    lv_obj_set_width(ui_Unit_Label_Battery_Voltage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Unit_Label_Battery_Voltage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Unit_Label_Battery_Voltage, 68);
    lv_obj_set_y(ui_Unit_Label_Battery_Voltage, 5);
    lv_obj_set_align(ui_Unit_Label_Battery_Voltage, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Unit_Label_Battery_Voltage, "V");
    lv_obj_set_style_text_color(ui_Unit_Label_Battery_Voltage, lv_color_hex(0x94AEB4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Unit_Label_Battery_Voltage, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Unit_Label_Battery_Voltage, &ui_font_Medium, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Nav_Button_Group = lv_obj_create(ui_Group_Footer);
    lv_obj_set_width(ui_Nav_Button_Group, 236);
    lv_obj_set_height(ui_Nav_Button_Group, 50);
    lv_obj_set_align(ui_Nav_Button_Group, LV_ALIGN_RIGHT_MID);
    lv_obj_clear_flag(ui_Nav_Button_Group, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Nav_Button_Group, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Nav_Button_Group, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BTN_Driving = lv_obj_create(ui_Nav_Button_Group);
    lv_obj_set_height(ui_BTN_Driving, 40);
    lv_obj_set_width(ui_BTN_Driving, lv_pct(40));
    lv_obj_set_align(ui_BTN_Driving, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_BTN_Driving, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BTN_Driving, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BTN_Driving, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BTN_BG1 = lv_img_create(ui_BTN_Driving);
    lv_img_set_src(ui_BTN_BG1, &ui_img_menu_on_png);
    lv_obj_set_width(ui_BTN_BG1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BTN_BG1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BTN_BG1, 0);
    lv_obj_set_y(ui_BTN_BG1, 1);
    lv_obj_set_align(ui_BTN_BG1, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_BTN_BG1, LV_STATE_CHECKED);       /// States
    lv_obj_add_flag(ui_BTN_BG1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_BTN_BG1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_blend_mode(ui_BTN_BG1, LV_BLEND_MODE_ADDITIVE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_BTN_BG1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_BTN_BG1, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_ICN_Driving = lv_img_create(ui_BTN_Driving);
    lv_img_set_src(ui_ICN_Driving, &ui_img_icon_oilchange_png);
    lv_obj_set_width(ui_ICN_Driving, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ICN_Driving, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ICN_Driving, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ICN_Driving, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ICN_Driving, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BTN_Diagnostics = lv_obj_create(ui_Nav_Button_Group);
    lv_obj_set_height(ui_BTN_Diagnostics, 40);
    lv_obj_set_width(ui_BTN_Diagnostics, lv_pct(40));
    lv_obj_set_align(ui_BTN_Diagnostics, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_BTN_Diagnostics, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BTN_Diagnostics, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BTN_Diagnostics, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BTN_BG2 = lv_img_create(ui_BTN_Diagnostics);
    lv_img_set_src(ui_BTN_BG2, &ui_img_menu_on_png);
    lv_obj_set_width(ui_BTN_BG2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BTN_BG2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BTN_BG2, 0);
    lv_obj_set_y(ui_BTN_BG2, 1);
    lv_obj_set_align(ui_BTN_BG2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BTN_BG2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_BTN_BG2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_blend_mode(ui_BTN_BG2, LV_BLEND_MODE_ADDITIVE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_BTN_BG2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_BTN_BG2, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Icon_Diagnostics = lv_img_create(ui_BTN_Diagnostics);
    lv_img_set_src(ui_Icon_Diagnostics, &ui_img_190876488);
    lv_obj_set_width(ui_Icon_Diagnostics, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Icon_Diagnostics, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Icon_Diagnostics, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Icon_Diagnostics, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Icon_Diagnostics, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BTN_Lock = lv_obj_create(ui_Nav_Button_Group);
    lv_obj_set_height(ui_BTN_Lock, 40);
    lv_obj_set_width(ui_BTN_Lock, lv_pct(40));
    lv_obj_set_align(ui_BTN_Lock, LV_ALIGN_RIGHT_MID);
    lv_obj_clear_flag(ui_BTN_Lock, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BTN_Lock, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BTN_Lock, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BTN_BG3 = lv_img_create(ui_BTN_Lock);
    lv_img_set_src(ui_BTN_BG3, &ui_img_menu_on_png);
    lv_obj_set_width(ui_BTN_BG3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BTN_BG3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BTN_BG3, 0);
    lv_obj_set_y(ui_BTN_BG3, 1);
    lv_obj_set_align(ui_BTN_BG3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BTN_BG3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_BTN_BG3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_blend_mode(ui_BTN_BG3, LV_BLEND_MODE_ADDITIVE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_BTN_BG3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_BTN_BG3, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_ICN_Lock = lv_img_create(ui_BTN_Lock);
    lv_img_set_src(ui_ICN_Lock, &ui_img_icn_lock_png);
    lv_obj_set_width(ui_ICN_Lock, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ICN_Lock, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ICN_Lock, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ICN_Lock, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ICN_Lock, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Group_Oil_Change_Data_Panel = lv_obj_create(ui_Main);
    lv_obj_set_width(ui_Group_Oil_Change_Data_Panel, 260);
    lv_obj_set_height(ui_Group_Oil_Change_Data_Panel, 200);
    lv_obj_set_x(ui_Group_Oil_Change_Data_Panel, 0);
    lv_obj_set_y(ui_Group_Oil_Change_Data_Panel, -10);
    lv_obj_set_align(ui_Group_Oil_Change_Data_Panel, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_Group_Oil_Change_Data_Panel, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_Group_Oil_Change_Data_Panel, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Group_Oil_Change_Data_Panel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Group_Oil_Change_Data_Panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Group_Info_Panel_Title = lv_obj_create(ui_Group_Oil_Change_Data_Panel);
    lv_obj_set_width(ui_Group_Info_Panel_Title, 260);
    lv_obj_set_height(ui_Group_Info_Panel_Title, 46);
    lv_obj_set_align(ui_Group_Info_Panel_Title, LV_ALIGN_TOP_RIGHT);
    lv_obj_clear_flag(ui_Group_Info_Panel_Title, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Group_Info_Panel_Title, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Group_Info_Panel_Title, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Underline_Title_Oil_Change = lv_img_create(ui_Group_Info_Panel_Title);
    lv_img_set_src(ui_Underline_Title_Oil_Change, &ui_img_menu_line_png);
    lv_obj_set_width(ui_Underline_Title_Oil_Change, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Underline_Title_Oil_Change, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Underline_Title_Oil_Change, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_add_flag(ui_Underline_Title_Oil_Change, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Underline_Title_Oil_Change, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label_Oil_Change_Information = lv_label_create(ui_Group_Info_Panel_Title);
    lv_obj_set_width(ui_Label_Oil_Change_Information, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Oil_Change_Information, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_Oil_Change_Information, -19);
    lv_obj_set_y(ui_Label_Oil_Change_Information, 0);
    lv_obj_set_align(ui_Label_Oil_Change_Information, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_Label_Oil_Change_Information, "Oil Change Information");
    lv_obj_set_style_text_color(ui_Label_Oil_Change_Information, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_Oil_Change_Information, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Oil_Change_Information, &ui_font_Medium, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Group_Oil_Change_Info_Content = lv_obj_create(ui_Group_Oil_Change_Data_Panel);
    lv_obj_set_width(ui_Group_Oil_Change_Info_Content, 200);
    lv_obj_set_height(ui_Group_Oil_Change_Info_Content, 154);
    lv_obj_set_align(ui_Group_Oil_Change_Info_Content, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_clear_flag(ui_Group_Oil_Change_Info_Content, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Group_Oil_Change_Info_Content, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Group_Oil_Change_Info_Content, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Group_Oil_Change_Info_Content, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Group_Oil_Change_Info_Content, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Group_Oil_Change_Info_Content, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Group_Oil_Change_Info_Content, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Group_Battery_Voltage = lv_obj_create(ui_Group_Oil_Change_Info_Content);
    lv_obj_set_width(ui_Group_Battery_Voltage, 80);
    lv_obj_set_height(ui_Group_Battery_Voltage, 40);
    lv_obj_set_align(ui_Group_Battery_Voltage, LV_ALIGN_TOP_RIGHT);
    lv_obj_clear_flag(ui_Group_Battery_Voltage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Group_Battery_Voltage, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Group_Battery_Voltage, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Group_Battery_Voltage, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Group_Battery_Voltage, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Group_Battery_Voltage, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Group_Battery_Voltage, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_Flow_Rate = lv_label_create(ui_Group_Battery_Voltage);
    lv_obj_set_width(ui_Label_Flow_Rate, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Flow_Rate, LV_SIZE_CONTENT);    /// 1
    lv_label_set_text(ui_Label_Flow_Rate, "Flow Rate");
    lv_obj_set_style_text_color(ui_Label_Flow_Rate, lv_color_hex(0x94AEB4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_Flow_Rate, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Flow_Rate, &ui_font_Small, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Flow_Rate_Number = lv_label_create(ui_Group_Battery_Voltage);
    lv_obj_set_width(ui_Flow_Rate_Number, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Flow_Rate_Number, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Flow_Rate_Number, 2);
    lv_obj_set_y(ui_Flow_Rate_Number, 6);
    lv_obj_set_align(ui_Flow_Rate_Number, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Flow_Rate_Number, "0.0");
    lv_obj_set_style_text_color(ui_Flow_Rate_Number, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Flow_Rate_Number, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Flow_Rate_Number, &ui_font_Big, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Unit_Label_Flow_Rate = lv_label_create(ui_Group_Battery_Voltage);
    lv_obj_set_width(ui_Unit_Label_Flow_Rate, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Unit_Label_Flow_Rate, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Unit_Label_Flow_Rate, -20);
    lv_obj_set_y(ui_Unit_Label_Flow_Rate, -5);
    lv_obj_set_align(ui_Unit_Label_Flow_Rate, LV_ALIGN_BOTTOM_RIGHT);
    lv_label_set_text(ui_Unit_Label_Flow_Rate, "L");
    lv_obj_set_style_text_color(ui_Unit_Label_Flow_Rate, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Unit_Label_Flow_Rate, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Unit_Label_Flow_Rate, &ui_font_Small, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Group_Oil_Temp = lv_obj_create(ui_Group_Oil_Change_Info_Content);
    lv_obj_set_width(ui_Group_Oil_Temp, 80);
    lv_obj_set_height(ui_Group_Oil_Temp, 40);
    lv_obj_clear_flag(ui_Group_Oil_Temp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Group_Oil_Temp, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Group_Oil_Temp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Group_Oil_Temp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Group_Oil_Temp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Group_Oil_Temp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Group_Oil_Temp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_Oil_Temp = lv_label_create(ui_Group_Oil_Temp);
    lv_obj_set_width(ui_Label_Oil_Temp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Oil_Temp, LV_SIZE_CONTENT);    /// 1
    lv_label_set_text(ui_Label_Oil_Temp, "Oil Temp");
    lv_obj_set_style_text_color(ui_Label_Oil_Temp, lv_color_hex(0x94AEB4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_Oil_Temp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Oil_Temp, &ui_font_Small, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Oil_Temp_Number = lv_label_create(ui_Group_Oil_Temp);
    lv_obj_set_width(ui_Oil_Temp_Number, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Oil_Temp_Number, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Oil_Temp_Number, 2);
    lv_obj_set_y(ui_Oil_Temp_Number, 6);
    lv_obj_set_align(ui_Oil_Temp_Number, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Oil_Temp_Number, "74.8");
    lv_obj_set_style_text_color(ui_Oil_Temp_Number, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Oil_Temp_Number, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Oil_Temp_Number, &ui_font_Big, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_Unit_Celcius = lv_label_create(ui_Group_Oil_Temp);
    lv_obj_set_width(ui_Label_Unit_Celcius, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Unit_Celcius, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_Unit_Celcius, -20);
    lv_obj_set_y(ui_Label_Unit_Celcius, -5);
    lv_obj_set_align(ui_Label_Unit_Celcius, LV_ALIGN_BOTTOM_RIGHT);
    lv_label_set_text(ui_Label_Unit_Celcius, "°C");
    lv_obj_set_style_text_color(ui_Label_Unit_Celcius, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_Unit_Celcius, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Unit_Celcius, &ui_font_Small, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Group_Amount_Filled = lv_obj_create(ui_Group_Oil_Change_Info_Content);
    lv_obj_set_width(ui_Group_Amount_Filled, 80);
    lv_obj_set_height(ui_Group_Amount_Filled, 40);
    lv_obj_set_align(ui_Group_Amount_Filled, LV_ALIGN_RIGHT_MID);
    lv_obj_clear_flag(ui_Group_Amount_Filled, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Group_Amount_Filled, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Group_Amount_Filled, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Group_Amount_Filled, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Group_Amount_Filled, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Group_Amount_Filled, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Group_Amount_Filled, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_Filled = lv_label_create(ui_Group_Amount_Filled);
    lv_obj_set_width(ui_Label_Filled, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Filled, LV_SIZE_CONTENT);    /// 1
    lv_label_set_text(ui_Label_Filled, "FILLED");
    lv_obj_set_style_text_color(ui_Label_Filled, lv_color_hex(0x94AEB4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_Filled, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Filled, &ui_font_Small, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Amount_Filled_Number = lv_label_create(ui_Group_Amount_Filled);
    lv_obj_set_width(ui_Amount_Filled_Number, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Amount_Filled_Number, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Amount_Filled_Number, 2);
    lv_obj_set_y(ui_Amount_Filled_Number, 6);
    lv_obj_set_align(ui_Amount_Filled_Number, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Amount_Filled_Number, "0.0");
    lv_obj_set_style_text_color(ui_Amount_Filled_Number, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Amount_Filled_Number, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Amount_Filled_Number, &ui_font_Big, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Unit_Label_Litres = lv_label_create(ui_Group_Amount_Filled);
    lv_obj_set_width(ui_Unit_Label_Litres, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Unit_Label_Litres, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Unit_Label_Litres, -25);
    lv_obj_set_y(ui_Unit_Label_Litres, -5);
    lv_obj_set_align(ui_Unit_Label_Litres, LV_ALIGN_BOTTOM_RIGHT);
    lv_label_set_text(ui_Unit_Label_Litres, "L");
    lv_obj_set_style_text_color(ui_Unit_Label_Litres, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Unit_Label_Litres, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Unit_Label_Litres, &ui_font_Small, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Group_Amount_Extracted = lv_obj_create(ui_Group_Oil_Change_Info_Content);
    lv_obj_set_width(ui_Group_Amount_Extracted, 80);
    lv_obj_set_height(ui_Group_Amount_Extracted, 40);
    lv_obj_set_align(ui_Group_Amount_Extracted, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_Group_Amount_Extracted, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Group_Amount_Extracted, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Group_Amount_Extracted, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Group_Amount_Extracted, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Group_Amount_Extracted, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Group_Amount_Extracted, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Group_Amount_Extracted, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_Extracted = lv_label_create(ui_Group_Amount_Extracted);
    lv_obj_set_width(ui_Label_Extracted, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Extracted, LV_SIZE_CONTENT);    /// 1
    lv_label_set_text(ui_Label_Extracted, "EXTRACTED");
    lv_obj_set_style_text_color(ui_Label_Extracted, lv_color_hex(0x94AEB4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_Extracted, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Extracted, &ui_font_Small, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Amount_Extracted_Number = lv_label_create(ui_Group_Amount_Extracted);
    lv_obj_set_width(ui_Amount_Extracted_Number, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Amount_Extracted_Number, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Amount_Extracted_Number, 2);
    lv_obj_set_y(ui_Amount_Extracted_Number, 6);
    lv_obj_set_align(ui_Amount_Extracted_Number, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Amount_Extracted_Number, "0.0");
    lv_obj_set_style_text_color(ui_Amount_Extracted_Number, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Amount_Extracted_Number, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Amount_Extracted_Number, &ui_font_Big, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Unit_Label_Extracted_Litres = lv_label_create(ui_Group_Amount_Extracted);
    lv_obj_set_width(ui_Unit_Label_Extracted_Litres, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Unit_Label_Extracted_Litres, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Unit_Label_Extracted_Litres, -30);
    lv_obj_set_y(ui_Unit_Label_Extracted_Litres, -5);
    lv_obj_set_align(ui_Unit_Label_Extracted_Litres, LV_ALIGN_BOTTOM_RIGHT);
    lv_label_set_text(ui_Unit_Label_Extracted_Litres, "L");
    lv_obj_set_style_text_color(ui_Unit_Label_Extracted_Litres, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Unit_Label_Extracted_Litres, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Unit_Label_Extracted_Litres, &ui_font_Small, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Group_ETA = lv_obj_create(ui_Group_Oil_Change_Info_Content);
    lv_obj_set_width(ui_Group_ETA, 80);
    lv_obj_set_height(ui_Group_ETA, 40);
    lv_obj_set_align(ui_Group_ETA, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_clear_flag(ui_Group_ETA, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Group_ETA, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Group_ETA, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Group_ETA, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Group_ETA, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Group_ETA, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Group_ETA, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_ETA = lv_label_create(ui_Group_ETA);
    lv_obj_set_width(ui_Label_ETA, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_ETA, LV_SIZE_CONTENT);    /// 1
    lv_label_set_text(ui_Label_ETA, "ETA");
    lv_obj_set_style_text_color(ui_Label_ETA, lv_color_hex(0x94AEB4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_ETA, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_ETA, &ui_font_Small, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ETA_Time = lv_label_create(ui_Group_ETA);
    lv_obj_set_width(ui_ETA_Time, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ETA_Time, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ETA_Time, 2);
    lv_obj_set_y(ui_ETA_Time, 6);
    lv_obj_set_align(ui_ETA_Time, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_ETA_Time, "00:00");
    lv_obj_set_style_text_color(ui_ETA_Time, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ETA_Time, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ETA_Time, &ui_font_Big, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Group_Run_Time = lv_obj_create(ui_Group_Oil_Change_Info_Content);
    lv_obj_set_width(ui_Group_Run_Time, 80);
    lv_obj_set_height(ui_Group_Run_Time, 40);
    lv_obj_set_align(ui_Group_Run_Time, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_clear_flag(ui_Group_Run_Time, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Group_Run_Time, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Group_Run_Time, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Group_Run_Time, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Group_Run_Time, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Group_Run_Time, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Group_Run_Time, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_Run_Time = lv_label_create(ui_Group_Run_Time);
    lv_obj_set_width(ui_Label_Run_Time, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Run_Time, LV_SIZE_CONTENT);    /// 1
    lv_label_set_text(ui_Label_Run_Time, "TIME");
    lv_obj_set_style_text_color(ui_Label_Run_Time, lv_color_hex(0x94AEB4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_Run_Time, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Run_Time, &ui_font_Small, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Run_Time = lv_label_create(ui_Group_Run_Time);
    lv_obj_set_width(ui_Run_Time, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Run_Time, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Run_Time, 2);
    lv_obj_set_y(ui_Run_Time, 6);
    lv_obj_set_align(ui_Run_Time, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Run_Time, "00:00");
    lv_obj_set_style_text_color(ui_Run_Time, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Run_Time, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Run_Time, &ui_font_Big, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Group_Diagnostics = lv_obj_create(ui_Main);
    lv_obj_set_width(ui_Group_Diagnostics, 260);
    lv_obj_set_height(ui_Group_Diagnostics, 200);
    lv_obj_set_x(ui_Group_Diagnostics, 0);
    lv_obj_set_y(ui_Group_Diagnostics, -10);
    lv_obj_set_align(ui_Group_Diagnostics, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_Group_Diagnostics, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_Group_Diagnostics, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Group_Diagnostics, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Group_Diagnostics, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Group_Diagnostics_Information = lv_obj_create(ui_Group_Diagnostics);
    lv_obj_set_width(ui_Group_Diagnostics_Information, 260);
    lv_obj_set_height(ui_Group_Diagnostics_Information, 46);
    lv_obj_set_align(ui_Group_Diagnostics_Information, LV_ALIGN_TOP_RIGHT);
    lv_obj_clear_flag(ui_Group_Diagnostics_Information, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Group_Diagnostics_Information, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Group_Diagnostics_Information, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Title_BG1 = lv_img_create(ui_Group_Diagnostics_Information);
    lv_img_set_src(ui_Title_BG1, &ui_img_menu_line_png);
    lv_obj_set_width(ui_Title_BG1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Title_BG1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Title_BG1, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_add_flag(ui_Title_BG1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Title_BG1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label_Diagnostics_Title = lv_label_create(ui_Group_Diagnostics_Information);
    lv_obj_set_width(ui_Label_Diagnostics_Title, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Diagnostics_Title, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_Diagnostics_Title, -19);
    lv_obj_set_y(ui_Label_Diagnostics_Title, 0);
    lv_obj_set_align(ui_Label_Diagnostics_Title, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_Label_Diagnostics_Title, "Diagnostic Information");
    lv_obj_set_style_text_color(ui_Label_Diagnostics_Title, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_Diagnostics_Title, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Diagnostics_Title, &ui_font_Medium, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Group_Content1 = lv_obj_create(ui_Group_Diagnostics);
    lv_obj_set_width(ui_Group_Content1, 200);
    lv_obj_set_height(ui_Group_Content1, 154);
    lv_obj_set_align(ui_Group_Content1, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_clear_flag(ui_Group_Content1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Group_Content1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Group_Content1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Group_Content1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Group_Content1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Group_Content1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Group_Content1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Group_Charging = lv_obj_create(ui_Group_Content1);
    lv_obj_set_width(ui_Group_Charging, 80);
    lv_obj_set_height(ui_Group_Charging, 40);
    lv_obj_set_align(ui_Group_Charging, LV_ALIGN_TOP_RIGHT);
    lv_obj_clear_flag(ui_Group_Charging, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Group_Charging, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Group_Charging, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Group_Charging, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Group_Charging, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Group_Charging, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Group_Charging, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabeL_Charging = lv_label_create(ui_Group_Charging);
    lv_obj_set_width(ui_LabeL_Charging, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabeL_Charging, LV_SIZE_CONTENT);    /// 1
    lv_label_set_text(ui_LabeL_Charging, "CHARGING");
    lv_obj_set_style_text_color(ui_LabeL_Charging, lv_color_hex(0x94AEB4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabeL_Charging, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabeL_Charging, &ui_font_Small, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_Charging_Number = lv_label_create(ui_Group_Charging);
    lv_obj_set_width(ui_Label_Charging_Number, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Charging_Number, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_Charging_Number, 2);
    lv_obj_set_y(ui_Label_Charging_Number, 6);
    lv_obj_set_align(ui_Label_Charging_Number, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label_Charging_Number, "37");
    lv_obj_set_style_text_color(ui_Label_Charging_Number, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_Charging_Number, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Charging_Number, &ui_font_Big, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_Percent1 = lv_label_create(ui_Group_Charging);
    lv_obj_set_width(ui_Label_Percent1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Percent1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_Percent1, -44);
    lv_obj_set_y(ui_Label_Percent1, -5);
    lv_obj_set_align(ui_Label_Percent1, LV_ALIGN_BOTTOM_RIGHT);
    lv_label_set_text(ui_Label_Percent1, "%");
    lv_obj_set_style_text_color(ui_Label_Percent1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_Percent1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Percent1, &ui_font_Small, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Group_Distance = lv_obj_create(ui_Group_Content1);
    lv_obj_set_width(ui_Group_Distance, 80);
    lv_obj_set_height(ui_Group_Distance, 40);
    lv_obj_set_align(ui_Group_Distance, LV_ALIGN_RIGHT_MID);
    lv_obj_clear_flag(ui_Group_Distance, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Group_Distance, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Group_Distance, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Group_Distance, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Group_Distance, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Group_Distance, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Group_Distance, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_Distance = lv_label_create(ui_Group_Distance);
    lv_obj_set_width(ui_Label_Distance, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Distance, LV_SIZE_CONTENT);    /// 1
    lv_label_set_text(ui_Label_Distance, "DISTANCE");
    lv_obj_set_style_text_color(ui_Label_Distance, lv_color_hex(0x94AEB4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_Distance, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Distance, &ui_font_Small, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_Distance_Number = lv_label_create(ui_Group_Distance);
    lv_obj_set_width(ui_Label_Distance_Number, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Distance_Number, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_Distance_Number, 2);
    lv_obj_set_y(ui_Label_Distance_Number, 6);
    lv_obj_set_align(ui_Label_Distance_Number, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label_Distance_Number, "84.5");
    lv_obj_set_style_text_color(ui_Label_Distance_Number, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_Distance_Number, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Distance_Number, &ui_font_Big, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_km4 = lv_label_create(ui_Group_Distance);
    lv_obj_set_width(ui_Label_km4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_km4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_km4, -15);
    lv_obj_set_y(ui_Label_km4, -5);
    lv_obj_set_align(ui_Label_km4, LV_ALIGN_BOTTOM_RIGHT);
    lv_label_set_text(ui_Label_km4, "km");
    lv_obj_set_style_text_color(ui_Label_km4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_km4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_km4, &ui_font_Small, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Group_Complete = lv_obj_create(ui_Group_Content1);
    lv_obj_set_width(ui_Group_Complete, 80);
    lv_obj_set_height(ui_Group_Complete, 40);
    lv_obj_set_align(ui_Group_Complete, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_clear_flag(ui_Group_Complete, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Group_Complete, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Group_Complete, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Group_Complete, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Group_Complete, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Group_Complete, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Group_Complete, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_Complete = lv_label_create(ui_Group_Complete);
    lv_obj_set_width(ui_Label_Complete, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Complete, LV_SIZE_CONTENT);    /// 1
    lv_label_set_text(ui_Label_Complete, "COMPLETE");
    lv_obj_set_style_text_color(ui_Label_Complete, lv_color_hex(0x94AEB4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_Complete, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Complete, &ui_font_Small, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_Complete_Number = lv_label_create(ui_Group_Complete);
    lv_obj_set_width(ui_Label_Complete_Number, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Complete_Number, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_Complete_Number, 2);
    lv_obj_set_y(ui_Label_Complete_Number, 6);
    lv_obj_set_align(ui_Label_Complete_Number, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label_Complete_Number, "42");
    lv_obj_set_style_text_color(ui_Label_Complete_Number, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_Complete_Number, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Complete_Number, &ui_font_Big, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_Mins = lv_label_create(ui_Group_Complete);
    lv_obj_set_width(ui_Label_Mins, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Mins, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_Mins, -21);
    lv_obj_set_y(ui_Label_Mins, -5);
    lv_obj_set_align(ui_Label_Mins, LV_ALIGN_BOTTOM_RIGHT);
    lv_label_set_text(ui_Label_Mins, "mins");
    lv_obj_set_style_text_color(ui_Label_Mins, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_Mins, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Mins, &ui_font_Small, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Group_Battery_Indicator = lv_obj_create(ui_Group_Content1);
    lv_obj_set_width(ui_Group_Battery_Indicator, 100);
    lv_obj_set_height(ui_Group_Battery_Indicator, lv_pct(115));
    lv_obj_set_align(ui_Group_Battery_Indicator, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_Group_Battery_Indicator, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Group_Battery_Indicator, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Group_Battery_Indicator, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Particle_Group = lv_obj_create(ui_Group_Battery_Indicator);
    lv_obj_set_width(ui_Particle_Group, 50);
    lv_obj_set_height(ui_Particle_Group, 120);
    lv_obj_set_align(ui_Particle_Group, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Particle_Group, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Particle_Group, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Particle_Group, lv_color_hex(0x202420), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Particle_Group, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_clip_corner(ui_Particle_Group, true, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image_Particle1 = lv_img_create(ui_Particle_Group);
    lv_img_set_src(ui_Image_Particle1, &ui_img_particle_1_png);
    lv_obj_set_height(ui_Image_Particle1, 240);
    lv_obj_set_width(ui_Image_Particle1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_align(ui_Image_Particle1, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_Image_Particle1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image_Particle1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_blend_mode(ui_Image_Particle1, LV_BLEND_MODE_ADDITIVE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Wave_Group = lv_obj_create(ui_Group_Battery_Indicator);
    lv_obj_set_width(ui_Wave_Group, 50);
    lv_obj_set_height(ui_Wave_Group, 120);
    lv_obj_set_align(ui_Wave_Group, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Wave_Group, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Wave_Group, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Wave_Group, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Wave_Group, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_clip_corner(ui_Wave_Group, true, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Wave1 = lv_img_create(ui_Wave_Group);
    lv_img_set_src(ui_Wave1, &ui_img_water_2_png);
    lv_obj_set_width(ui_Wave1, 206);
    lv_obj_set_height(ui_Wave1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Wave1, 0);
    lv_obj_set_y(ui_Wave1, 66);
    lv_obj_set_align(ui_Wave1, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_Wave1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Wave1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image_Particle2 = lv_img_create(ui_Wave_Group);
    lv_img_set_src(ui_Image_Particle2, &ui_img_particle_3_png);
    lv_obj_set_height(ui_Image_Particle2, 240);
    lv_obj_set_width(ui_Image_Particle2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_align(ui_Image_Particle2, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_Image_Particle2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image_Particle2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_blend_mode(ui_Image_Particle2, LV_BLEND_MODE_ADDITIVE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Wave2 = lv_img_create(ui_Wave_Group);
    lv_img_set_src(ui_Wave2, &ui_img_water_1_png);
    lv_obj_set_width(ui_Wave2, 206);
    lv_obj_set_height(ui_Wave2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Wave2, 0);
    lv_obj_set_y(ui_Wave2, 70);
    lv_obj_add_flag(ui_Wave2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Wave2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image_Particle3 = lv_img_create(ui_Wave_Group);
    lv_img_set_src(ui_Image_Particle3, &ui_img_particle_2_png);
    lv_obj_set_height(ui_Image_Particle3, 240);
    lv_obj_set_width(ui_Image_Particle3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_Image_Particle3, 3);
    lv_obj_set_y(ui_Image_Particle3, 0);
    lv_obj_set_align(ui_Image_Particle3, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_Image_Particle3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image_Particle3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_blend_mode(ui_Image_Particle3, LV_BLEND_MODE_ADDITIVE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image_Battery_BG = lv_img_create(ui_Group_Battery_Indicator);
    lv_img_set_src(ui_Image_Battery_BG, &ui_img_battery_bg_png);
    lv_obj_set_width(ui_Image_Battery_BG, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image_Battery_BG, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image_Battery_BG, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image_Battery_BG, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image_Battery_BG, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Image_Battery_BG, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Image_Battery_BG, lv_color_hex(0x438DB5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Image_Battery_BG, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Image_Battery_BG, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Image_Battery_BG, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image_Flash = lv_img_create(ui_Group_Battery_Indicator);
    lv_img_set_src(ui_Image_Flash, &ui_img_icn_charge_png);
    lv_obj_set_width(ui_Image_Flash, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image_Flash, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image_Flash, -13);
    lv_obj_set_y(ui_Image_Flash, 0);
    lv_obj_set_align(ui_Image_Flash, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_Image_Flash, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image_Flash, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Group_Pin_Code = lv_obj_create(ui_Main);
    lv_obj_set_width(ui_Group_Pin_Code, 260);
    lv_obj_set_height(ui_Group_Pin_Code, 200);
    lv_obj_set_x(ui_Group_Pin_Code, 0);
    lv_obj_set_y(ui_Group_Pin_Code, -10);
    lv_obj_set_align(ui_Group_Pin_Code, LV_ALIGN_RIGHT_MID);
    lv_obj_clear_flag(ui_Group_Pin_Code, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Group_Pin_Code, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Group_Pin_Code, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Group_Admin_Title = lv_obj_create(ui_Group_Pin_Code);
    lv_obj_set_width(ui_Group_Admin_Title, 260);
    lv_obj_set_height(ui_Group_Admin_Title, 46);
    lv_obj_set_align(ui_Group_Admin_Title, LV_ALIGN_TOP_RIGHT);
    lv_obj_clear_flag(ui_Group_Admin_Title, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Group_Admin_Title, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Group_Admin_Title, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Title_BG2 = lv_img_create(ui_Group_Admin_Title);
    lv_img_set_src(ui_Title_BG2, &ui_img_menu_line_png);
    lv_obj_set_width(ui_Title_BG2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Title_BG2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Title_BG2, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_add_flag(ui_Title_BG2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Title_BG2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label_Unlock = lv_label_create(ui_Group_Admin_Title);
    lv_obj_set_width(ui_Label_Unlock, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Unlock, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_Unlock, -15);
    lv_obj_set_y(ui_Label_Unlock, 0);
    lv_obj_set_align(ui_Label_Unlock, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_Label_Unlock, "Enter Admin Pin Code");
    lv_obj_set_style_text_color(ui_Label_Unlock, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_Unlock, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Unlock, &ui_font_Medium, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Group_Pin_Numbers = lv_obj_create(ui_Group_Pin_Code);
    lv_obj_set_width(ui_Group_Pin_Numbers, 180);
    lv_obj_set_height(ui_Group_Pin_Numbers, 174);
    lv_obj_set_x(ui_Group_Pin_Numbers, -8);
    lv_obj_set_y(ui_Group_Pin_Numbers, 36);
    lv_obj_set_align(ui_Group_Pin_Numbers, LV_ALIGN_RIGHT_MID);
    lv_obj_clear_flag(ui_Group_Pin_Numbers, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Group_Pin_Numbers, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Group_Pin_Numbers, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Group_Pin_Numbers, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Group_Pin_Numbers, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Group_Pin_Numbers, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Group_Pin_Numbers, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button_Pin_Code_1 = lv_btn_create(ui_Group_Pin_Numbers);
    lv_obj_set_width(ui_Button_Pin_Code_1, 55);
    lv_obj_set_height(ui_Button_Pin_Code_1, 36);
    lv_obj_set_x(ui_Button_Pin_Code_1, -60);
    lv_obj_set_y(ui_Button_Pin_Code_1, 0);
    lv_obj_set_align(ui_Button_Pin_Code_1, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_Button_Pin_Code_1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button_Pin_Code_1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button_Pin_Code_1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button_Pin_Code_1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Button_Pin_Code_1, &ui_img_pin_line_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_1 = lv_label_create(ui_Button_Pin_Code_1);
    lv_obj_set_width(ui_Label_1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label_1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_1, "1");
    lv_obj_set_style_text_color(ui_Label_1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label_1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_1, &ui_font_Big, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Pin_Add1 = lv_img_create(ui_Button_Pin_Code_1);
    lv_img_set_src(ui_Pin_Add1, &ui_img_pin_on_png);
    lv_obj_set_width(ui_Pin_Add1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Pin_Add1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Pin_Add1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Pin_Add1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Pin_Add1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_blend_mode(ui_Pin_Add1, LV_BLEND_MODE_ADDITIVE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_Pin_Add1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button_Pin_Code_2 = lv_btn_create(ui_Group_Pin_Numbers);
    lv_obj_set_width(ui_Button_Pin_Code_2, 55);
    lv_obj_set_height(ui_Button_Pin_Code_2, 36);
    lv_obj_set_align(ui_Button_Pin_Code_2, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_Button_Pin_Code_2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button_Pin_Code_2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button_Pin_Code_2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button_Pin_Code_2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Button_Pin_Code_2, &ui_img_pin_line_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_2 = lv_label_create(ui_Button_Pin_Code_2);
    lv_obj_set_width(ui_Label_2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label_2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_2, "2");
    lv_obj_set_style_text_color(ui_Label_2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label_2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_2, &ui_font_Big, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Pin_Add2 = lv_img_create(ui_Button_Pin_Code_2);
    lv_img_set_src(ui_Pin_Add2, &ui_img_pin_on_png);
    lv_obj_set_width(ui_Pin_Add2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Pin_Add2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Pin_Add2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Pin_Add2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Pin_Add2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_blend_mode(ui_Pin_Add2, LV_BLEND_MODE_ADDITIVE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_Pin_Add2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button_Pin_Code_3 = lv_btn_create(ui_Group_Pin_Numbers);
    lv_obj_set_width(ui_Button_Pin_Code_3, 55);
    lv_obj_set_height(ui_Button_Pin_Code_3, 36);
    lv_obj_set_x(ui_Button_Pin_Code_3, 60);
    lv_obj_set_y(ui_Button_Pin_Code_3, 0);
    lv_obj_set_align(ui_Button_Pin_Code_3, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_Button_Pin_Code_3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button_Pin_Code_3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button_Pin_Code_3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button_Pin_Code_3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Button_Pin_Code_3, &ui_img_pin_line_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_3 = lv_label_create(ui_Button_Pin_Code_3);
    lv_obj_set_width(ui_Label_3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label_3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_3, "3");
    lv_obj_set_style_text_color(ui_Label_3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label_3, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_3, &ui_font_Big, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Pin_Add3 = lv_img_create(ui_Button_Pin_Code_3);
    lv_img_set_src(ui_Pin_Add3, &ui_img_pin_on_png);
    lv_obj_set_width(ui_Pin_Add3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Pin_Add3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Pin_Add3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Pin_Add3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Pin_Add3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_blend_mode(ui_Pin_Add3, LV_BLEND_MODE_ADDITIVE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_Pin_Add3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button_Pin_Code_4 = lv_btn_create(ui_Group_Pin_Numbers);
    lv_obj_set_width(ui_Button_Pin_Code_4, 55);
    lv_obj_set_height(ui_Button_Pin_Code_4, 36);
    lv_obj_set_x(ui_Button_Pin_Code_4, -60);
    lv_obj_set_y(ui_Button_Pin_Code_4, 36);
    lv_obj_set_align(ui_Button_Pin_Code_4, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_Button_Pin_Code_4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button_Pin_Code_4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button_Pin_Code_4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button_Pin_Code_4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Button_Pin_Code_4, &ui_img_pin_line_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_4 = lv_label_create(ui_Button_Pin_Code_4);
    lv_obj_set_width(ui_Label_4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label_4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_4, "4");
    lv_obj_set_style_text_color(ui_Label_4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label_4, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_4, &ui_font_Big, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Pin_Add4 = lv_img_create(ui_Button_Pin_Code_4);
    lv_img_set_src(ui_Pin_Add4, &ui_img_pin_on_png);
    lv_obj_set_width(ui_Pin_Add4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Pin_Add4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Pin_Add4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Pin_Add4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Pin_Add4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_blend_mode(ui_Pin_Add4, LV_BLEND_MODE_ADDITIVE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_Pin_Add4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button_Pin_Code_5 = lv_btn_create(ui_Group_Pin_Numbers);
    lv_obj_set_width(ui_Button_Pin_Code_5, 55);
    lv_obj_set_height(ui_Button_Pin_Code_5, 36);
    lv_obj_set_x(ui_Button_Pin_Code_5, 0);
    lv_obj_set_y(ui_Button_Pin_Code_5, 36);
    lv_obj_set_align(ui_Button_Pin_Code_5, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_Button_Pin_Code_5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button_Pin_Code_5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button_Pin_Code_5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button_Pin_Code_5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Button_Pin_Code_5, &ui_img_pin_line_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_5 = lv_label_create(ui_Button_Pin_Code_5);
    lv_obj_set_width(ui_Label_5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label_5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_5, "5");
    lv_obj_set_style_text_color(ui_Label_5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label_5, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_5, &ui_font_Big, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Pin_Add5 = lv_img_create(ui_Button_Pin_Code_5);
    lv_img_set_src(ui_Pin_Add5, &ui_img_pin_on_png);
    lv_obj_set_width(ui_Pin_Add5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Pin_Add5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Pin_Add5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Pin_Add5, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Pin_Add5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_blend_mode(ui_Pin_Add5, LV_BLEND_MODE_ADDITIVE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_Pin_Add5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button_Pin_Code_6 = lv_btn_create(ui_Group_Pin_Numbers);
    lv_obj_set_width(ui_Button_Pin_Code_6, 55);
    lv_obj_set_height(ui_Button_Pin_Code_6, 36);
    lv_obj_set_x(ui_Button_Pin_Code_6, 60);
    lv_obj_set_y(ui_Button_Pin_Code_6, 36);
    lv_obj_set_align(ui_Button_Pin_Code_6, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_Button_Pin_Code_6, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button_Pin_Code_6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button_Pin_Code_6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button_Pin_Code_6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Button_Pin_Code_6, &ui_img_pin_line_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_6 = lv_label_create(ui_Button_Pin_Code_6);
    lv_obj_set_width(ui_Label_6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label_6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_6, "6");
    lv_obj_set_style_text_color(ui_Label_6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label_6, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_6, &ui_font_Big, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Pin_Add6 = lv_img_create(ui_Button_Pin_Code_6);
    lv_img_set_src(ui_Pin_Add6, &ui_img_pin_on_png);
    lv_obj_set_width(ui_Pin_Add6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Pin_Add6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Pin_Add6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Pin_Add6, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Pin_Add6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_blend_mode(ui_Pin_Add6, LV_BLEND_MODE_ADDITIVE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_Pin_Add6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button_Pin_Code_7 = lv_btn_create(ui_Group_Pin_Numbers);
    lv_obj_set_width(ui_Button_Pin_Code_7, 55);
    lv_obj_set_height(ui_Button_Pin_Code_7, 36);
    lv_obj_set_x(ui_Button_Pin_Code_7, -60);
    lv_obj_set_y(ui_Button_Pin_Code_7, 72);
    lv_obj_set_align(ui_Button_Pin_Code_7, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_Button_Pin_Code_7, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button_Pin_Code_7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button_Pin_Code_7, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button_Pin_Code_7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Button_Pin_Code_7, &ui_img_pin_line_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_7 = lv_label_create(ui_Button_Pin_Code_7);
    lv_obj_set_width(ui_Label_7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label_7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_7, "7");
    lv_obj_set_style_text_color(ui_Label_7, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label_7, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_7, &ui_font_Big, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Pin_Add7 = lv_img_create(ui_Button_Pin_Code_7);
    lv_img_set_src(ui_Pin_Add7, &ui_img_pin_on_png);
    lv_obj_set_width(ui_Pin_Add7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Pin_Add7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Pin_Add7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Pin_Add7, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Pin_Add7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_blend_mode(ui_Pin_Add7, LV_BLEND_MODE_ADDITIVE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_Pin_Add7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button_Pin_Code_8 = lv_btn_create(ui_Group_Pin_Numbers);
    lv_obj_set_width(ui_Button_Pin_Code_8, 55);
    lv_obj_set_height(ui_Button_Pin_Code_8, 36);
    lv_obj_set_x(ui_Button_Pin_Code_8, 0);
    lv_obj_set_y(ui_Button_Pin_Code_8, 72);
    lv_obj_set_align(ui_Button_Pin_Code_8, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_Button_Pin_Code_8, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button_Pin_Code_8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button_Pin_Code_8, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button_Pin_Code_8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Button_Pin_Code_8, &ui_img_pin_line_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_8 = lv_label_create(ui_Button_Pin_Code_8);
    lv_obj_set_width(ui_Label_8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label_8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_8, "8");
    lv_obj_set_style_text_color(ui_Label_8, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label_8, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_8, &ui_font_Big, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Pin_Add8 = lv_img_create(ui_Button_Pin_Code_8);
    lv_img_set_src(ui_Pin_Add8, &ui_img_pin_on_png);
    lv_obj_set_width(ui_Pin_Add8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Pin_Add8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Pin_Add8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Pin_Add8, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Pin_Add8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_blend_mode(ui_Pin_Add8, LV_BLEND_MODE_ADDITIVE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_Pin_Add8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button_Pin_Code_9 = lv_btn_create(ui_Group_Pin_Numbers);
    lv_obj_set_width(ui_Button_Pin_Code_9, 55);
    lv_obj_set_height(ui_Button_Pin_Code_9, 36);
    lv_obj_set_x(ui_Button_Pin_Code_9, 60);
    lv_obj_set_y(ui_Button_Pin_Code_9, 72);
    lv_obj_set_align(ui_Button_Pin_Code_9, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_Button_Pin_Code_9, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button_Pin_Code_9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button_Pin_Code_9, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button_Pin_Code_9, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Button_Pin_Code_9, &ui_img_pin_line_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_9 = lv_label_create(ui_Button_Pin_Code_9);
    lv_obj_set_width(ui_Label_9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label_9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_9, "9");
    lv_obj_set_style_text_color(ui_Label_9, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label_9, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_9, &ui_font_Big, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Pin_Add9 = lv_img_create(ui_Button_Pin_Code_9);
    lv_img_set_src(ui_Pin_Add9, &ui_img_pin_on_png);
    lv_obj_set_width(ui_Pin_Add9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Pin_Add9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Pin_Add9, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Pin_Add9, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Pin_Add9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_blend_mode(ui_Pin_Add9, LV_BLEND_MODE_ADDITIVE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_Pin_Add9, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button_Pin_Code_X = lv_btn_create(ui_Group_Pin_Numbers);
    lv_obj_set_width(ui_Button_Pin_Code_X, 55);
    lv_obj_set_height(ui_Button_Pin_Code_X, 36);
    lv_obj_set_x(ui_Button_Pin_Code_X, -60);
    lv_obj_set_y(ui_Button_Pin_Code_X, 108);
    lv_obj_set_align(ui_Button_Pin_Code_X, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_Button_Pin_Code_X, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button_Pin_Code_X, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button_Pin_Code_X, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button_Pin_Code_X, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Button_Pin_Code_X, &ui_img_pin_line_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Pin_Add10 = lv_img_create(ui_Button_Pin_Code_X);
    lv_img_set_src(ui_Pin_Add10, &ui_img_pin_on_png);
    lv_obj_set_width(ui_Pin_Add10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Pin_Add10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Pin_Add10, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Pin_Add10, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Pin_Add10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_blend_mode(ui_Pin_Add10, LV_BLEND_MODE_ADDITIVE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_Pin_Add10, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image_X = lv_img_create(ui_Button_Pin_Code_X);
    lv_img_set_src(ui_Image_X, &ui_img_icn_x_png);
    lv_obj_set_width(ui_Image_X, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image_X, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image_X, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image_X, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image_X, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button_Pin_Code_0 = lv_btn_create(ui_Group_Pin_Numbers);
    lv_obj_set_width(ui_Button_Pin_Code_0, 55);
    lv_obj_set_height(ui_Button_Pin_Code_0, 36);
    lv_obj_set_x(ui_Button_Pin_Code_0, 0);
    lv_obj_set_y(ui_Button_Pin_Code_0, 108);
    lv_obj_set_align(ui_Button_Pin_Code_0, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_Button_Pin_Code_0, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button_Pin_Code_0, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button_Pin_Code_0, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button_Pin_Code_0, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Button_Pin_Code_0, &ui_img_pin_line_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_0 = lv_label_create(ui_Button_Pin_Code_0);
    lv_obj_set_width(ui_Label_0, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_0, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label_0, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_0, "0");
    lv_obj_set_style_text_color(ui_Label_0, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_0, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label_0, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_0, &ui_font_Big, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Pin_Add11 = lv_img_create(ui_Button_Pin_Code_0);
    lv_img_set_src(ui_Pin_Add11, &ui_img_pin_on_png);
    lv_obj_set_width(ui_Pin_Add11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Pin_Add11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Pin_Add11, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Pin_Add11, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Pin_Add11, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_blend_mode(ui_Pin_Add11, LV_BLEND_MODE_ADDITIVE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_Pin_Add11, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button_Pin_Code_Confirm = lv_btn_create(ui_Group_Pin_Numbers);
    lv_obj_set_width(ui_Button_Pin_Code_Confirm, 55);
    lv_obj_set_height(ui_Button_Pin_Code_Confirm, 36);
    lv_obj_set_x(ui_Button_Pin_Code_Confirm, 60);
    lv_obj_set_y(ui_Button_Pin_Code_Confirm, 108);
    lv_obj_set_align(ui_Button_Pin_Code_Confirm, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_Button_Pin_Code_Confirm, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button_Pin_Code_Confirm, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button_Pin_Code_Confirm, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button_Pin_Code_Confirm, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Button_Pin_Code_Confirm, &ui_img_pin_line_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Pin_Add12 = lv_img_create(ui_Button_Pin_Code_Confirm);
    lv_img_set_src(ui_Pin_Add12, &ui_img_pin_on_png);
    lv_obj_set_width(ui_Pin_Add12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Pin_Add12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Pin_Add12, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Pin_Add12, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Pin_Add12, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_blend_mode(ui_Pin_Add12, LV_BLEND_MODE_ADDITIVE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_Pin_Add12, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image_Ok = lv_img_create(ui_Button_Pin_Code_Confirm);
    lv_img_set_src(ui_Image_Ok, &ui_img_icn_ok_png);
    lv_obj_set_width(ui_Image_Ok, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image_Ok, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image_Ok, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image_Ok, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image_Ok, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_Slider_Extract, ui_event_Slider_Extract, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BTN_BG1, ui_event_BTN_BG1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BTN_BG2, ui_event_BTN_BG2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BTN_BG3, ui_event_BTN_BG3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button_Pin_Code_1, ui_event_Button_Pin_Code_1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button_Pin_Code_2, ui_event_Button_Pin_Code_2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button_Pin_Code_3, ui_event_Button_Pin_Code_3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button_Pin_Code_4, ui_event_Button_Pin_Code_4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button_Pin_Code_5, ui_event_Button_Pin_Code_5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button_Pin_Code_6, ui_event_Button_Pin_Code_6, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button_Pin_Code_7, ui_event_Button_Pin_Code_7, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button_Pin_Code_8, ui_event_Button_Pin_Code_8, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button_Pin_Code_9, ui_event_Button_Pin_Code_9, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button_Pin_Code_X, ui_event_Button_Pin_Code_X, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button_Pin_Code_0, ui_event_Button_Pin_Code_0, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button_Pin_Code_Confirm, ui_event_Button_Pin_Code_Confirm, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Main, ui_event_Main, LV_EVENT_ALL, NULL);

}
